const mongoose = require('mongoose');

const premiseSchema = new mongoose.Schema({
    applicationType: { type: String,  },
    applicantName: { type: String,  },
    organizationName: { type: String,  },
    zepraClientId: { type: String },
    phoneNumber: { type: String,  },
    emailAddress: { type: String,  },
    premisesType: { type: String,  },
    physicalAddress: { type: String,  },
    provinceCity: { type: String,  },
    gpsCoordinates: { type: String },
    landlordName: { type: String },
    landlordContact: { type: String },
    leaseAgreement: { type: String,  },
    leaseStartDate: { type: Date,  },
    leaseEndDate: { type: Date,  },
    monthlyRent: { type: Number,  },
    totalLeaseValue: { type: Number,  },
    projectName: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' },
    purposeOfPremises: { type: String },
    areaSize: { type: Number },
    zoningType: { type: String },
    zoningApproval: { type: String },
    environmentalClearance: { type: String },
    buildingSafetyCert: { type: String },
    otherDocs: { type: [String] },
    declaration: {   },
    authorizedPersonName: { type: String,  },
    submissionDate: { type: Date,  },
    userId:{ type: String, required: true },
    digitalSignature: { type: String,  },
}, { timestamps: true });

module.exports = mongoose.model('Application', premiseSchema);
